version: '2.0'

services:
  storage:
    # image: openzipkin/zipkin-elasticsearch
    # container_name: elasticsearch
    # image: carlozleite/es-swarm
    # container_name: elasticsearch
    # environment: 
    #   - SERVICE_NAME=elasticsearch 
    #   - ES_JAVA_OPTS='-Xms512m -Xmx512m' 
    # ports: 
    #   - 9200:9201/tcp
    image: openzipkin/zipkin-mysql
    container_name: mysql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # - STORAGE_TYPE=elasticsearch
      # # Point the zipkin at the storage backend
      # - ES_HOSTS=http://elasticsearch:9201
    ports:
      - 9411:9411/tcp
    depends_on:
      - storage
    # links:
    #   - storage:elasticsearch
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500/tcp
  app:
    build: .
    container_name: pocresilienciajs
    ports:
      - 8000:8000/tcp 
      - 3004:3004/tcp 
      - 3005:3005/tcp
    depends_on:
      - zipkin
      - consul
    links: 
      - zipkin:zipkin
      - consul:consul
