version: '2.0'

services:
  storage:
    # image: openzipkin/zipkin-elasticsearch
    # container_name: elasticsearch
    # image: carlozleite/es-swarm
    # container_name: elasticsearch
    # environment: 
    #   - SERVICE_NAME=elasticsearch 
    #   - ES_JAVA_OPTS='-Xms512m -Xmx512m' 
    # ports: 
    #   - 9200:9201/tcp
    image: openzipkin/zipkin-mysql
    container_name: mysql
  # kafka:
  #   image: spotify/kafka
  #   container_name: kafka
  #   environment:
  #     - ADVERTISED_PORT=9092
  #     - ADVERTISED_HOST=172.18.0.2
  #   ports:
  #     - 2181:2181
  #     - 9092:9092
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # - KAFKA_ZOOKEEPER=kafka
      # - STORAGE_TYPE=elasticsearch
      # # Point the zipkin at the storage backend
      # - ES_HOSTS=http://elasticsearch:9201
    ports:
      - 9411:9411/tcp
    depends_on:
      - storage
      # - kafka
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500/tcp
  app:
    build: .
    container_name: pocresilienciajs
    env_file:
      - poc.env
    ports:
      - 8000:8000/tcp 
      - 3004:3004/tcp 
      - 3005:3005/tcp
    depends_on:
      - zipkin
      - consul
      # - kafka
    links: 
      - zipkin:zipkin
      - consul:consul
      # - kafka:kafka
