version: '2.0'

services:
  storage:
    image: carlozleite/es-swarm
    container_name: elasticsearch
    environment: 
      - env SERVICE_NAME=elasticsearch 
      - env ES_JAVA_OPTS='-Xms512m -Xmx512m' 
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=http://elasticsearch:9200
    ports:
      - 9411:9411/tcp
    depends_on:
      - storage
  app:
    build: .
    container_name: pocresilienciajs
    ports:
      - 8000:8000/tcp 
      - 3004:3004/tcp 
      - 3005:3005/tcp
    depends_on:
      - zipkin
    links: 
      - zipkin:zipkin
